name: bullseye
description: Immutable and functional primitives for Dart.
homepage: https://github.com/MiSikora/Bullseye
version: 0.1.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
